# Generated by Django 5.2.6 on 2025-10-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='products')),
                ('p_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quntaty', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='app.catagory')),
            ],
        ),
    ]
