# Generated by Django 5.2.6 on 2025-10-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cuponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponcode',
            name='discount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuponcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
