# Generated by Django 5.2.6 on 2025-10-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cuponcode_discount_alter_cuponcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponcode',
            name='code',
            field=models.TextField(),
        ),
    ]
