# Generated by Django 5.2.6 on 2025-10-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cuponcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponcode',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
