# Generated by Django 5.2.6 on 2025-10-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cuponcode_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='f_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
