# Generated by Django 5.2.6 on 2025-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='f_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='checkout',
            name='city',
            field=models.CharField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='lname',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
