# Generated by Django 5.2.6 on 2025-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_cart_f_total_remove_cart_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Cash on Delivery', 'COD'), ('paypal', 'paypal')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
