# Generated by Django 5.2.6 on 2025-10-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_checkout_payment_method_alter_checkout_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='payment_status',
            new_name='order_status',
        ),
    ]
